services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Qwerty13"
    ports:
        - 1435:1433
  dbinit:
    build:
      context: ../Geometry.Db
    command: 
      - "Server=db,1433;database=Geometry;User Id=sa;Password=Qwerty13;Persist Security Info=False;TrustServerCertificate=true"
    depends_on:
      - db
  app:
    build:
      context: ../..
      dockerfile: ./src/Geometry.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__GeometryDatabase: "Server=db,1433;database=Geometry;User Id=sa;Password=Qwerty13;Persist Security Info=False;TrustServerCertificate=true"
    ports:
      - 5000:80
    depends_on:
      - db
      - dbinit